2016-04-14 23:52:54,250 - requests_oauthlib.oauth1_auth - DEBUG - Signing request <PreparedRequest [POST]> using client <Client nonce=None, signature_method=HMAC-SHA1, realm=None, encoding=utf-8, timestamp=None, resource_owner_secret=****, decoding=None, verifier=None, signature_type=AUTH_HEADER, rsa_key=None, resource_owner_key=711680708222128128-XRUg8vuqnjklE4RnqGXCFyJ6WZnG4Sx, client_secret=****, callback_uri=None, client_key=0IqUcNNGuKaY59epn9E3jhinY>
2016-04-14 23:52:54,250 - requests_oauthlib.oauth1_auth - DEBUG - Including body in call to sign: True
2016-04-14 23:52:54,252 - oauthlib.oauth1.rfc5849 - DEBUG - Collected params: [(u'delimited', u'length'), (u'oauth_nonce', u'113414284892208889261460677974'), (u'oauth_timestamp', u'1460677974'), (u'oauth_consumer_key', u'0IqUcNNGuKaY59epn9E3jhinY'), (u'oauth_signature_method', u'HMAC-SHA1'), (u'oauth_version', u'1.0'), (u'oauth_token', u'711680708222128128-XRUg8vuqnjklE4RnqGXCFyJ6WZnG4Sx'), (u'track', u'a,the,i,you,u'), (u'language', u'en')]
2016-04-14 23:52:54,252 - oauthlib.oauth1.rfc5849 - DEBUG - Normalized params: delimited=length&language=en&oauth_consumer_key=0IqUcNNGuKaY59epn9E3jhinY&oauth_nonce=113414284892208889261460677974&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1460677974&oauth_token=711680708222128128-XRUg8vuqnjklE4RnqGXCFyJ6WZnG4Sx&oauth_version=1.0&track=a%2Cthe%2Ci%2Cyou%2Cu
2016-04-14 23:52:54,252 - oauthlib.oauth1.rfc5849 - DEBUG - Normalized URI: https://stream.twitter.com/1.1/statuses/filter.json
2016-04-14 23:52:54,253 - oauthlib.oauth1.rfc5849 - DEBUG - Base signing string: POST&https%3A%2F%2Fstream.twitter.com%2F1.1%2Fstatuses%2Ffilter.json&delimited%3Dlength%26language%3Den%26oauth_consumer_key%3D0IqUcNNGuKaY59epn9E3jhinY%26oauth_nonce%3D113414284892208889261460677974%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1460677974%26oauth_token%3D711680708222128128-XRUg8vuqnjklE4RnqGXCFyJ6WZnG4Sx%26oauth_version%3D1.0%26track%3Da%252Cthe%252Ci%252Cyou%252Cu
2016-04-14 23:52:54,253 - oauthlib.oauth1.rfc5849 - DEBUG - Signature: K1MZfy08dUa2+EXUvUyPg5a2UHk=
2016-04-14 23:52:54,253 - requests_oauthlib.oauth1_auth - DEBUG - Updated url: https://stream.twitter.com/1.1/statuses/filter.json?delimited=length
2016-04-14 23:52:54,254 - requests_oauthlib.oauth1_auth - DEBUG - Updated headers: {u'Content-Length': u'39', u'Content-Type': u'application/x-www-form-urlencoded', u'Authorization': u'OAuth oauth_nonce="113414284892208889261460677974", oauth_timestamp="1460677974", oauth_version="1.0", oauth_signature_method="HMAC-SHA1", oauth_consumer_key="0IqUcNNGuKaY59epn9E3jhinY", oauth_token="711680708222128128-XRUg8vuqnjklE4RnqGXCFyJ6WZnG4Sx", oauth_signature="K1MZfy08dUa2%2BEXUvUyPg5a2UHk%3D"'}
2016-04-14 23:52:54,254 - requests_oauthlib.oauth1_auth - DEBUG - Updated body: u'track=a%2Cthe%2Ci%2Cyou%2Cu&language=en'
2016-04-14 23:52:54,256 - requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): stream.twitter.com
2016-04-14 23:52:54,485 - requests.packages.urllib3.connectionpool - DEBUG - "POST /1.1/statuses/filter.json?delimited=length HTTP/1.1" 200 None
2016-04-14 23:52:54,696 - streamparse.storm.component - ERROR - Exception in Tweets.run()
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/streamparse/storm/component.py", line 489, in run
    self._run()
  File "/usr/lib/python2.7/site-packages/streamparse/storm/spout.py", line 150, in _run
    self.next_tuple()
  File "spouts/tweets.py", line 79, in next_tuple
    self.emit([tweet.text, tweet.place])
  File "/usr/lib/python2.7/site-packages/streamparse/storm/spout.py", line 99, in emit
    need_task_ids=need_task_ids)
  File "/usr/lib/python2.7/site-packages/streamparse/storm/component.py", line 463, in emit
    self.send_message(msg)
  File "/usr/lib/python2.7/site-packages/streamparse/storm/component.py", line 363, in send_message
    wrapped_msg = "{}\nend\n".format(json.dumps(message))
  File "/usr/lib64/python2.7/site-packages/simplejson/__init__.py", line 380, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python2.7/site-packages/simplejson/encoder.py", line 275, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python2.7/site-packages/simplejson/encoder.py", line 357, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib64/python2.7/site-packages/simplejson/encoder.py", line 252, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: Place(_api=<tweepy.api.API object at 0x28a6bd0>, country_code=u'US', url=u'https://api.twitter.com/1.1/geo/id/93b7643d8c54f6a7.json', country=u'United States', place_type=u'city', bounding_box=BoundingBox(_api=<tweepy.api.API object at 0x28a6bd0>, type=u'Polygon', coordinates=[[[-112.004989, 41.108787], [-112.004989, 41.153638], [-111.899558, 41.153638], [-111.899558, 41.108787]]]), full_name=u'South Weber, UT', attributes={}, id=u'93b7643d8c54f6a7', name=u'South Weber') is not JSON serializable
